# Recharge power needed to recharge battery
required-power: 2

# Whether recharge power should be taken on recharge
take-power: true

# BatteryTimer delay in seconds. The amount of time when a battery loses one power when placed
bt-delay: 10

# BatteryRecharger delay in seconds. The amount of time when a battery regains one power when recharging
br-delay: 5

# Overcharge enabled? Will batteries explode when they're overcharged? 
overcharge: true

# Max power, if above is set to 'true' an explosion will occur when reached
max-power: 5